# docker-compose.yml

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "7433:5432"
    volumes:
      - ./db/database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql

  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    env_file:
      - .env      

  #vector database with persistent storage
  vecdb:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vecdb
    ports:
      - 6433:5432      
    volumes:
      - ./vecdb:/var/lib/postgresql/database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  langfuse:
     image: langfuse/langfuse:2
     environment:
       DATABASE_URL: postgresql://postgres:postgres@vecdb:5432/langfuse
       NEXTAUTH_URL: http://localhost:3000
       NEXTAUTH_SECRET: mysecret
       SALT: mysalt
       ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
       LANGFUSE_INIT_ORG_ID: my-org
       LANGFUSE_INIT_PROJECT_ID: my-project
       LANGFUSE_INIT_PROJECT_PUBLIC_KEY: lf_pk_1234567890
       LANGFUSE_INIT_PROJECT_SECRET_KEY: lf_sk_1234567890
       LANGFUSE_INIT_EMAIL: admin@example.com
       LANGFUSE_INIT_PASSWORD: adminpassword      
     ports:
       - "3000:3000"
     depends_on:
       vecdb:
         condition: service_healthy

  # langfuse-dev:
  #   image: langfuse/langfuse:2
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@vecdb:6433/langfuse
  #     NEXTAUTH_URL: http://localhost:3000
  #     NEXTAUTH_SECRET: mysecret
  #     SALT: mysalt
  #     ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
  #     LANGFUSE_INIT_ORG_ID: my-org
  #     LANGFUSE_INIT_PROJECT_ID: my-project
  #     LANGFUSE_INIT_PROJECT_PUBLIC_KEY: lf_pk_1234567890
  #     LANGFUSE_INIT_PROJECT_SECRET_KEY: lf_sk_1234567890
  #     LANGFUSE_INIT_EMAIL: admin@example.com
  #     LANGFUSE_INIT_PASSWORD: adminpassword      
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     vecdb:
  #       condition: service_healthy
  #   #profiles: ["dev"]